import { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import Data from "../data.json";
import Card from "../components/Card";
import AOS from "aos";

import "aos/dist/aos.css"; // You can also use <link> for styles
import Container from "../components/Container";
import BottomPlayer from "../components/BottomPlayer";
import { useUserContext } from "../context/userContext";
import COMPONENT from "../components/COMPONENT";
// ..
export default function Home() {
  const { page, isMenu } = useUserContext();

  useEffect(() => {
    AOS.init();
  });
  console.log("%c JUKEGA NAIII ", "background: #252; color: #bada55");

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <COMPONENT />
      {page !== "playingnow" && <BottomPlayer />}
    </div>
  );
}
